### ISSUE TITLE
Release with clang 6

### ISSUE THREAD

**Issue by thejuskambi** [CastXML/CastXMLSuperbuild#20]
I  can see that the source and binaries  are built for only clang version 5. How can I upgrade it to clang 6 or when can I expect a new version.

**Comment by thewtex** [comment]
The source has been updated in #19. We anticipate updating CastXML and the binaries within the week.

CC: @bradking

**Comment by thewtex** [comment]
The binaries are now available here:

 https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/57b5de948d777f10f2696370

**Comment by 625781186** [comment]
@thewtex
Can you provide a the binaries with clang 7?

![image](https://user-images.githubusercontent.com/30521429/71621897-1531be80-2c0d-11ea-8af6-6a7fb9349230.png)

Thanks very much!

**Comment by thewtex** [comment]
@625781186 WIP to build with LLVM 9 is here:

  https://github.com/CastXML/CastXMLSuperbuild/pull/28

but I will not have time to look into the remaining build error for a while.
