### ISSUE TITLE
castxml v0.4.4 in tar file actually v0.4.3

### ISSUE THREAD

**Issue by jjd35** [CastXML/CastXMLSuperbuild#46]
Trying to download the linux tar file specified in the readme. Here is the link:

https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/57b5de948d777f10f2696370

when I go to v0.4.4, download the tar file  and extract. I noticed doing castxml --version shows 0.4.3 as the version.

**Comment by thewtex** [comment]
v0.4.5 has been uploaded:

 https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/622960ab4acac99f421349b8

Please give it a try.
