### ISSUE TITLE
zlib dependency

### ISSUE THREAD

**Issue by SimonRit** [CastXML/CastXMLSuperbuild#50]
ITK recently upgraded castxml (InsightSoftwareConsortium/ITK@438938a911c46daca240e8cade91c2409321e990). The [new windows version](https://data.kitware.com/api/v1/item/637d2d6411dab8142820b935/download) requires a zlib1__.dll file which was not required by the [previous version](https://data.kitware.com/api/v1/item/6337040411dab81428208759/download). Is this intentional and, if yes, how do you suggest to get this dll? The problem occurs when building RTK on a self-hosted machine see [here](https://github.com/RTKConsortium/RTK/actions/runs/3580536341/jobs/6029685049).

**Comment by SimonRit** [comment]
In case that helps, maybe @tbirdso or @LucasGandel have a clue?

**Comment by tbirdso** [comment]
Hi @SimonRit , I don't seem mention of zlib in the run you've linked, could you provide more information on where you see the new DLL requirement?

**Comment by tbirdso** [comment]
I can confirm that I am able to reproduce.

1. Download `castxml-windows.zip`: https://github.com/CastXML/CastXMLSuperbuild/releases/tag/v0.4.8
2. Unzip and navigate to `castxml-bin`
3. Try to run CastXML: `.\castxml --version`

Output in popup window:
```
The code execution cannot proceed because zlib1__.dll was not found. Reinstalling the program may fix this problem.
```

Unfortunately I'm not familiar with how CastXML or ITK consume zlib, perhaps @thewtex or @bradking could weigh in?

**Comment by SimonRit** [comment]
I ended up downloading from a [link](https://github.com/rust-lang/rust/files/6550164/zlib1__.zip) provided in rust-lang/rust#85422 which is not ideal...

**Comment by thewtex** [comment]
Hi @SimonRit ,

I assume that the hosted system is running Windows 11? The GitHub Hosted runners do not, which is why they do not have this issue.

> I ended up downloading from a link provided in rust-lang/rust#85422 which is not ideal...

You may as well keep this work around. It may also be possible to point the build [to `castxml-windows-win11.zip` ](https://data.kitware.com/#collection/57b5c9e58d777f126827f5a1/folder/637d0a8011dab8142820b92a).  This was addressed in ITK post 5.3.0 here: https://github.com/InsightSoftwareConsortium/ITK/pull/3767

**Comment by SimonRit** [comment]
No, it's windows 10. And it's actually since InsightSoftwareConsortium/ITK#3767 that it's not working... I can confirm that the win11 version works, maybe the [test](https://github.com/InsightSoftwareConsortium/ITK/pull/3767/files#diff-e7b9b1d2d1251e3340d02c7aae095ff229a0490fad2ff108c71eadc011961deeR43) on CMAKE_HOST_SYSTEM_VERSION should be modified?

**Comment by SimonRit** [comment]
(BTW, my Windows version 10.0.19044, just below 10.0.22000!)
