### ISSUE TITLE
Unexpected compiler version, expected Clang 15.0.0 or newer

### ISSUE THREAD

**Issue by MikhailGorobets** [CastXML/CastXMLSuperbuild#53]
It may be worth considering updating `clang` to its latest version
On `MSVC14.35.32215` this error appears.
![image](https://user-images.githubusercontent.com/25492259/236889531-01f5731f-4c40-463e-a29b-8c9b22fbe4b4.png)
Although based on the `yvals_core.h` header, it seems that `clang 11.0.0` is sufficient for building with `MSVC 14.29.30133`.

**Comment by thewtex** [comment]
:+1: Bumped to LLVM 18 https://github.com/CastXML/CastXMLSuperbuild/releases/tag/v0.6.5

**Comment by MikhailGorobets** [comment]
Thanks you!
